### ISSUE TITLE
error Calendar.current.dateComponents

### ISSUE THREAD

**Issue by badfranco** [FCiottoli/eCalendar#1]
<img width="893" alt="screen shot 2016-08-19 at 2 38 31 am" src="https://cloud.githubusercontent.com/assets/11565568/17802467/18019a3e-65b6-11e6-88f7-f8e5f00b4efe.png">

how can i fix this error ?

**Comment by FCiottoli** [comment]
Can you post error message, please?

For syntax error: this code is written in Swift 3.0, for Xcode 8 beta 4 and may not work with other release.

**Comment by badfranco** [comment]
<img width="899" alt="screen shot 2016-08-20 at 10 17 53 pm" src="https://cloud.githubusercontent.com/assets/11565568/17835169/22f667ca-6724-11e6-9842-04a0df92e306.png">


I'm on 8 beta 3

**Comment by FCiottoli** [comment]
soon I will publish an update to the latest release of Swift

**Comment by FCiottoli** [comment]
Code works with Xcode beta 6.
